version: '3'

services:
  consul:
    image: consul:1.2.2

  rabbit:
    image: earthquakesan/rabbitmq:feature_consul
    deploy:
      replicas: 3
      update_config:
        parallelism: 5
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      #mode: global
      placement:
        constraints: 
          - "node.labels.org.hobbit.type == worker"
    environment:
      - RABBITMQ_ERLANG_COOKIE="s3CR3tc00k13"  
    ports:
      - 15672:15672
    command: sh -c "sleep 10; rabbitmq-server;"

networks:
  default:
    driver: overlay
